show databases;
use miniprojectjava;
create table company(number int(1), companyname varchar(25),srno int(2),Question varchar(250), key(number));
create table branch(number int(1), branchname varchar(25),srno int(2),Question varchar(250), key(number));
create table miscellaneous(number int(1), point varchar(25),srno int(2),Question varchar(250), key(number));
create table prepareresume(number int(1),point varchar(25), srno int(2),tips varchar(250),key(number));
create table actionverbs(number int(1),point varchar(25),srno int(1), verbs varchar(1000), key(number));
create table resumesections(number int(1),point varchar(25), srno int(1), sections varchar(100),key(number));
create table currenttopics(number int(1),point varchar(25), srno int(2), topics varchar(250),key(number));
create table tips(number int(1),point varchar(25), srno int(2), tips varchar(250),key(number));
create table interviewtips(number int(1),point varchar(25), srno int(2), tips varchar(250),key(number));
create table bodylanguagetips(number int(1),point varchar(25), srno int(2), tips varchar(250), key(number));
create table commonmistakes(number int(1),point varchar(25), srno int(2), tips varchar(250),key(number));
create table confidencetips(number int(1),point varchar(25), srno int(2), tips varchar(250),key(number));
insert into company values(1, 'Amazon', 1,'Tell me something about yourself.'); 
insert into company values(1,'Amazon', 2,'In how many different ways can letters of the word PRAISE be arranged'); 
insert into company values(1,'Amazon', 3,'The C declaration int A[5][7] contains x elements, each of these elements is itself an array containing y integers. What is the value of 2x+y?'); 
insert into company values(1,'Amazon', 4,'What is the order to access the elements of a push down stack?'); 
insert into company values(1,'Amazon', 5,'What is the function of Layer 2 Switch?');
insert into company values(2,'Dell', 1,'What do you know about Dell?'); 
insert into company values(2,'Dell', 2,'Differentiate between declaration and definition.?');
insert into company values(2,'Dell', 3,'What is insertion Sort code?');
insert into company values(2,'Dell', 4,'List the advantages of inheritances.');
insert into company values(2,'Dell', 5,'Can you name the founder and chairman of DELL.');
insert into company values(3,'Goldman Sachs', 1,'Why do you want to join Goldman Sachs?');  
insert into company values(3,'Goldman Sachs', 2,'What is the exchange rate between the Euro and the American dollar?');
insert into company values(3,'Goldman Sachs', 3,'Why do you need synchronisation?');
insert into company values(3,'Goldman Sachs', 4,'How to find how much memory your program will need?');
insert into company values(3,'Goldman Sachs', 5,'Are you open for relocations?');
insert into company values(4,'Microsoft', 1,'What are Microsoft security patches?');
insert into company values(4,'Microsoft', 2,'What is not a characteristics of a modern DBMS?');
insert into company values(4,'Microsoft', 3,'What is the difference between HTML and XML?');
insert into company values(4,'Microsoft', 4,'Tell any 4 of your favourite products from Microsoft.');
insert into company values(4,'Microsoft', 5,'What is polymorphism?');
insert into company values(5,'Samsung', 1,'Where are Samsung Headquarters?');
insert into company values(5,'Samsung', 2,'What is the immediate superclass of the Applet class?');
insert into company values(5,'Samsung', 3,'What is minimal super key in DBMS?');  
insert into company values(5,'Samsung', 4,'Define B+ tree');
insert into company values(5,'Samsung', 5,'What are the different types of arrays?');                          
insert into branch values(6,'CS/IT', 1,'What is the recent trend in the IT industry');
insert into branch values(6,'CS/IT', 2, 'What are the 4 basics of OOP?');
insert into branch values(6,'CS/IT', 3, 'What is the difference between RAM and ROM?');
insert into branch values(6,'CS/IT', 4, 'What is the role of interpersonal communication in the career of an IT technician?');
insert into branch values(6,'CS/IT', 5, 'What is troubleshooting process?');
insert into branch values(7,'E&TC', 1, 'What is microcontroller?');
insert into branch values(7,'E&TC', 2, 'Explain what is the difference between inductance and resistance.');
insert into branch values(7,'E&TC', 3, 'Why do we need biasing for Transistor and Mosfet?');
insert into branch values(7,'E&TC', 4, 'How to calculate knee point voltage?');
insert into branch values(7,'E&TC', 5, 'What is Transponder?');
insert into miscellaneous values(8,'Behavioral', 1, 'Give an example of a time when you set a goal and were able to meet or achieve it');
insert into miscellaneous values(8,'Behavioral', 2, 'Describe a time when you were faced with a stressful situation and how you overcame the situation');
insert into miscellaneous values(8,'Behavioral', 3, 'Tell me about a time when you went overtime a deadline. ');
insert into miscellaneous values(8,'Behavioral', 4, 'What is the biggest contribution you made to your current role?');
insert into miscellaneous values(8,'Behavioral', 5, 'What are you most proud of in your working career?');
insert into miscellaneous values(9,'Guesstimate', 1, 'What is the market size of the apparel in India?');
insert into miscellaneous values(9,'Guesstimate', 2, 'How many red swift cars are there in Delhi?');
insert into miscellaneous values(9,'Guesstimate', 3, 'How many litres of paint is required to paint an airplane?');
insert into miscellaneous values(9,'Guesstimate', 4, 'Estimate the total length of roads in your city.');
insert into miscellaneous values(9,'Guesstimate', 5, 'What is the distance between New York and Delhi?');
insert into miscellaneous values(10,'Stress Interview', 1, 'If you caught a colleague cheating on his expense, what would you do?');
insert into miscellaneous values(10,'Stress Interview', 2, 'What would the person who likes you least in the world say about you?');
insert into miscellaneous values(10,'Stress Interview', 3, 'How do you feel this interview is going?');
insert into miscellaneous values(10,'Stress Interview', 4, 'Where do you see yourselves in next 5 years?');
insert into miscellaneous values(10,'Stress Interview', 5, 'Is there anything you would like to ask me?');
insert into prepareresume values(11,'Tip',1, 'The format should be visually attractive and professional at the same time.');
insert into prepareresume values(11,'Tip',2, 'Be clear and honest.');
insert into prepareresume values(11,'Tip',3, 'Donot unnecessarily increase the length of a sentence');
insert into prepareresume values(11,'Tip',4, 'The photograph attached must be clicked while you are dressed in formals.');
insert into prepareresume values(11,'Tip',5, 'The resume shouldnnt exceed 2 pages.');
insert into actionverbs values(12,'To Note',1, 'The action verbs catch attention and make your sentence easy to comprehend. ');
insert into actionverbs values(12,'To Note',2,'Use following action verbs: ');
insert into actionverbs values(12,'Example',1, 'Adventurous ');
insert into actionverbs values(12,'Example',2,'Approachable');
insert into actionverbs values(12,'Example',3,'Charismatic');
insert into actionverbs values(12,'Example',4,'Confident');
insert into actionverbs values(12,'Example',5,'Punctual');
insert into actionverbs values(12,'Example',6,'Responsible');
insert into actionverbs values(12,'Example',7,'Devoted');
insert into actionverbs values(12,'Example',8,'Organised');
insert into resumesections values(13,'SECTION',1, 'HEADER- It should contain your identity and information to contact you.');
insert into resumesections values(13,'SECTION',2, 'OBJECTIVES- Your objective should include the position wanted, functinal area and industry wanted.');
insert into resumesections values(13,'SECTION',3, 'EDUCATIONAL QUALIFICATIONS- Write all qualifications from 10th to present.');
insert into resumesections values(13,'SECTION',4, 'PROJECTS/INTERNSHIPS/EXPERIENCES');
insert into resumesections values(13,'SECTION',5, 'SKILLS- Inclue you soft skills, core skills and IT skills in this section.');
insert into resumesections values(13,'SECTION',6, 'INTERESTS');
insert into resumesections values(13,'SECTION',7, 'ACHIEVEMENTS');
insert into currenttopics values(14,'EDUCATIONAL',1,'Examination- has it killed education?');
insert into currenttopics values(14,'EDUCATIONAL',2,'Privatization of higher education.');
insert into currenttopics values(14,'EDUCATIONAL',3,'Education in rural areas.');
insert into currenttopics values(14,'EDUCATIONAL',4,'Brain drain and the Indian economy.');
insert into currenttopics values(14,'LANGUAGE',5,'There is no right way of doing the wrong thing.');
insert into currenttopics values(14,'LANGUAGE',6,'A person should not be too honest; Straight trees are cut first.');
insert into currenttopics values(14,'LANGUAGE',7,'All work and no play makes Jack a dull boy.');
insert into currenttopics values(14,'POLITICS',8,'Should the voters be given a NOTA choice?');
insert into currenttopics values(14,'POLITICS',9,'Retirement age of politicians.');
insert into currenttopics values(14,'POLITICS',10,'What India needs is a dictatorship.');
insert into tips values(15,'Tip',1,'Confidence is must.');
insert into tips values(15,'Tip',2,'Listen to other people and their ideas seriously.');
insert into tips values(15,'Tip',3,'Communicate clearly and loud enough so that everyone can recieve it well.');
insert into tips values(15,'Tip',4,'Keep an eye contact when speaking to others.');
insert into tips values(15,'Tip',5,'Go with the flow and never miss out the discussion.');
insert into interviewtips values(16,'Tip',1,'Research about the company/industry, whether it is growing or stable.');
insert into interviewtips values(16,'Tip',2,'Analyze yourself.');
insert into interviewtips values(16,'Tip',3,'You never get a second chance to make a first impression.');
insert into interviewtips values(16,'Tip',4,'Analyze the job description properly.');
insert into interviewtips values(16,'Tip',5,'Be happy and enthusiastic during the interview.');
insert into bodylanguagetips values(17,'Tip',1, 'Sit and stand up straight.');
insert into bodylanguagetips values(17,'Tip',2, 'Smile throughout the interview.');
insert into bodylanguagetips values(17,'Tip',3, 'Make a perfect eye contact throughout the interview.');
insert into bodylanguagetips values(17,'Tip',4, 'Do not put your elbows on the table. ');
insert into bodylanguagetips values(17,'Tip',5, 'Use hand gestures while speaking.');
insert into commonmistakes values(18,'Common Mistake',1,'Do not tel jokes until you are very comfortable with the interviewer.');
insert into commonmistakes values(18,'Common Mistake',2,'Never get personal while answering any question.');
insert into commonmistakes values(18,'Common Mistake',3,'Even if you love to talk, know your limits.');
insert into commonmistakes values(18,'Common Mistake',4,'Do  not lean back and be relaxed in an interview.');
insert into commonmistakes values(18,'Common Mistake',5,'Poor fittings, fancy clothes can ruin the whole interview.');
insert into confidencetips values(19,'Tip',1,'Make firm eye contact.');
insert into confidencetips values(19,'Tip',2,'Shake hands properly.');
insert into confidencetips values(19,'Tip',3,'Never go unprepared');
insert into confidencetips values(19,'Tip',4,'Be on time');
insert into confidencetips values(19,'Tip',5,'Nod along.');
insert into prepareresume values(11,'Tip',6, 'Maintian clarity. It should create a greater impact within short period.');
insert into prepareresume values(11,'Tip',7, 'Use bullet points rather than paragraphs.');
insert into prepareresume values(11,'Tip',8, 'Stay different. Do not copy.');
insert into prepareresume values(11,'Tip',9, 'Proof read the final version.');
insert into prepareresume values(11,'Tip',10, 'Remove repititive words from your resume. Use action verbs.');
create table rating(experience varchar(25),rating int(2),suggestions varchar(400), key(rating));



